### ISSUE TITLE
Crash Upon Entering Settings

### ISSUE THREAD

**Issue by Yowlen** [arpitkh96/AmazeFileManager#543] opened 2017-05-01 01:53 UTC
As soon as I tap on Settings in the left sidebar, the app crashes. I've sent a couple reports on the previous version of Amaze, and just sent another one using the newly-released 3.1.2 RC2 from the Play Store. I put "Crash upon entering Settings page." in the feedback area for the latest one. I don't think it was bugged on earlier versions, but I'm not sure. I'm running Android 5.1.1, and cleared the data to make sure that wasn't the cause before sending the report.

**Comment by vishal0071** [comment] 2017-05-01 03:18
This is why I keep insisting beta testers to test everything. There are 2000 testers enrolled not one of them is interested in actually testing it reporting anything.
The crash is being caused by Fingerprint API which I used recently for validating decryption of files, not being found.
I'll push an urgent fix only when I see more reports coming otherwise you would need to wait for another stable release.

**Comment by vishal0071** [comment] 2017-05-01 06:13
Fixed with new v3.1.2 RC3 
Test and report

**Closed by vishal0071** 2017-05-01 06:13 UTC

**Comment by Yowlen** [comment] 2017-05-01 18:05
lol. Yeah, a lot of people aren't really beta testers. They just want the new features & they ignore how buggy it gets.

Thanks. It's fixed.
