### ISSUE TITLE
App will crash while copying big file

### ISSUE THREAD

**Issue by kspang** [arpitkh96/AmazeFileManager#471] opened 2017-03-06 03:59 UTC
3.1.2 Beta 9

About 100MB file: Works
About 125MB file: App crashed.

Source and destination paths are both in flash memory.

From logcat:
[Logcat.txt](https://github.com/arpitkh96/AmazeFileManager/files/820119/Logcat.txt)

**Comment by vishal0071** [comment] 2017-03-06 04:08
Are both source and target in internal memory?

**Comment by kspang** [comment] 2017-03-06 04:22
Yes.. both in internal memory.

**Comment by vishal0071** [comment] 2017-03-06 05:03
The logcat you presented doesn't tell the exact cause of crash. If it crashes then you should send the crash report via crash dialog (send feedback or report option).

**Comment by kspang** [comment] 2017-03-06 05:06
Yes, crash reports were sent 2 times.
You should receive them about 3 hours ago.
I'll generate one more and send to you now.

**Comment by vishal0071** [comment] 2017-03-06 05:14
Alright, I'll be working on the fix ASAP.

**Comment by kspang** [comment] 2017-03-06 05:16
Additional info to reproduce the issue.

Please get the file below for your test.
[BigFile.zip](https://github.com/arpitkh96/AmazeFileManager/files/820190/BigFile.zip)

My steps:
1. Unzip this file to "Download" folder. (my case: /storage/emulated/0/Download/)
2. Create a sub folder named "temp" in the "Download" folder.
3. Copy and paste the BigFile.bmp from "./Download" to "./Download/tmp".
The app will crash.

**Comment by vishal0071** [comment] 2017-03-06 05:24
Can't reproduce it on my device, but don't worry I got this. I might actually put up some beta release before a final one so do keep yourself opted to beta to test it.

**Comment by vishal0071** [comment] 2017-03-06 05:24
BTW how did you compress a 125 MB file to 177KB?

**Comment by kspang** [comment] 2017-03-06 05:27
The uncompressed file is merely a bitmap file repetitive bytes values.
Typical zip app can compress this easily.

**Comment by JORGETECH** [comment] 2017-03-11 13:28
I can confirm this bug happening on my device. I have the same problem copying multiple files at the same time on the external SD card. My Android version is 4.4.2.

**Comment by vishal0071** [comment] 2017-04-30 22:33
Test in latest version v3.1.2 RC2 and report

**Comment by JORGETECH** [comment] 2017-05-01 10:56
It seems to be fixed in 3.1.2 RC3 (at least for me). I tried copying the big file from the compressed file and copying several files at the same time and both of those operations were completed with no errors both on the internal SD card and the external one.

**Comment by kspang** [comment] 2017-05-01 11:28
Tested without issue in 3.1.2RC3.
Thanks.

**Closed** 2017-05-01 19:43 UTC
Labels: bug
